---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: test-ansible-role-ferm
    box: debian/buster64
    config_options:
      synced_folder: false
    memory: 256
    cpus: 1
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../shared/inventory/group_vars
verifier:
  name: ansible
