- hosts: all
  become: yes
  vars:
    ferm_enabled: yes
    ferm_rules_group_all:
      00-verbatim:
        '00':
          content: |
            @def $foo = bar;
      01-policies:
        '00':
          chain: INPUT
          domains: [ip, ip6]
          rules:
            - rule: policy ACCEPT
            - rule: mod state state INVALID DROP
              comment: "Drop invalid packets"
            - rule: mod state state (ESTABLISHED RELATED) ACCEPT
              comment: "Allow already established sessions"
            - rule: interface lo ACCEPT
              comment: "Allow traffic from localhost interface"
    
        '01':
          chain: OUTPUT
          domains: [ip, ip6]
          rules:
            - rule: policy ACCEPT
    
        '02':
          chain: FORWARD
          domains: [ip, ip6]
          rules:
            - rule: policy DROP
    
      02-icmp:
        '00':
          chain: INPUT
          domains: [ip]
          rules:
            - rule: proto icmp icmp-type (3 8 11) ACCEPT
              comment: "Allow dest unreachable, ping and time exceeded messages"
        '01':
          chain: INPUT
          domains: [ip]
          rules:
            - rule: proto ipv6-icmp ACCEPT
              comment: "Allow all ipv6 icmp messages"
    
      10-mgmt:
        '00':
          chain: INPUT
          domains: [ip, ip6]
          rules:
            - rule: proto tcp dport ssh saddr (192.168.178.0/28 2001:db8::/64) ACCEPT
              comment: "Allow SSH from my trusted IPs"
    
      99-allow-vagrant:
       '00':
          chain: INPUT
          domains: [ ip ]
          rules:
            - rule: proto tcp dport ssh saddr {{ ansible_host ~ '/24' }} ACCEPT
    
      99-chain-foo:
        '00':
          chain: foo
    
      99-multiple-chains:
        '00':
          chain: [ bar, baz ]
          rules:
            - rule: daddr 192.0.2.1 ACCEPT
              
      99-reject:
        '00':
          chain: INPUT
          domains: [ip, ip6]
          rules:
            - rule: REJECT reject-with icmp-host-prohibited
    ferm_rules_group_all_override:
      01-policies:
        '01': "{{ omit }}"
        '02':
          chain: FORWARD
          domains: [ip, ip6]
          rules:
            - rule: policy ACCEPT        
  tasks:

    - include_role:
        name: ansible-role-ferm
